// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test_SocorroExpress_login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test_SocorroExpress_login', async function() {
    await driver.get("http://127.0.0.1:5500/Front-end/html/login.html")
    await driver.manage().window().setRect({ width: 1086, height: 816 })
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.id("email")).sendKeys("joao.pedro1@gmail.com")
    await driver.findElement(By.id("senha")).click()
    await driver.findElement(By.id("senha")).click()
    await driver.findElement(By.id("senha")).sendKeys("Joao12345")
    await driver.findElement(By.id("loginButton")).click()
  })
})
