// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test_SocorroExpress_Endereco', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test_SocorroExpress_Endereco', async function() {
    await driver.get("http://127.0.0.1:5500/Front-end/html/perfil.html")
    await driver.manage().window().setRect({ width: 1086, height: 816 })
    await driver.findElement(By.id("enderecos")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("nome_end")).click()
    await driver.findElement(By.id("nome_end")).sendKeys("Casa")
    await driver.findElement(By.id("endereco")).click()
    await driver.findElement(By.id("endereco")).click()
    await driver.findElement(By.id("endereco")).sendKeys("Alameda Cassaquera - Barcelona, São Caetano do Sul - SP, Brasil")
    {
      const element = await driver.findElement(By.css(".form-group:nth-child(3)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("salvarBtn")).click()
    await driver.findElement(By.css(".list-group-item:nth-child(1) .bi-pencil")).click()
    await driver.findElement(By.id("nome_end")).click()
    await driver.findElement(By.id("nome_end")).click()
    await driver.findElement(By.id("nome_end")).sendKeys("House")
    await driver.findElement(By.id("endereco")).click()
    await driver.findElement(By.id("endereco")).sendKeys("Alameda São Caetano - Santa Maria, São Caetano do Sul - SP, 09070-210, Brasil")
    {
      const element = await driver.findElement(By.id("salvarBtn"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
  })
})
