// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test_SocorroExpress_cadastroPerfil', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test_SocorroExpress_cadastroPerfil', async function() {
    await driver.get("http://127.0.0.1:5500/Front-end/html/solicitacao.html")
    await driver.manage().window().setRect({ width: 1084, height: 816 })
    await driver.findElement(By.id("informacoes-pessoais")).click()
    await driver.findElement(By.css(".text-center .btn")).click()
    await driver.findElement(By.id("data_nasc")).click()
    await driver.findElement(By.id("data_nasc")).click()
    await driver.findElement(By.id("data_nasc")).sendKeys("0002-07-26")
    await driver.findElement(By.id("data_nasc")).sendKeys("0020-07-26")
    await driver.findElement(By.id("data_nasc")).sendKeys("0200-07-26")
    await driver.findElement(By.id("data_nasc")).sendKeys("2002-07-26")
    await driver.findElement(By.id("sexo")).click()
    await driver.findElement(By.id("sexo")).sendKeys("Masculino")
    await driver.findElement(By.id("tipo_sang")).click()
    await driver.findElement(By.id("tipo_sang")).sendKeys("A+")
    await driver.findElement(By.id("doenca_pre")).click()
    await driver.findElement(By.id("doenca_pre")).sendKeys("Nenhuma")
    await driver.findElement(By.id("remedio")).click()
    await driver.findElement(By.id("remedio")).sendKeys("Nenhum")
    await driver.findElement(By.id("descricao")).click()
    await driver.findElement(By.id("descricao")).sendKeys("Nenhuma")
    await driver.findElement(By.id("perfil")).click()
    await driver.findElement(By.id("perfil")).click()
    await driver.findElement(By.css(".row")).click()
  })
})
