// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test_SocorroExpress_trocaSenhaEmail', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test_SocorroExpress_trocaSenhaEmail', async function() {
    await driver.get("http://127.0.0.1:5500/Front-end/html/solicitacao.html")
    await driver.manage().window().setRect({ width: 1084, height: 816 })
    await driver.findElement(By.id("informacoes-pessoais")).click()
    await driver.findElement(By.id("dados_conta")).click()
    await driver.findElement(By.css(".d-flex:nth-child(2) .btn")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("joao.pedro2@gmail.com")
    await driver.findElement(By.id("confirmar")).click()
    await driver.findElement(By.id("confirmar")).sendKeys("joao.pedro2@gmail.com")
    await driver.findElement(By.id("salvar")).click()
    await driver.get("http://127.0.0.1:5500/Front-end/html/dados.html")
    await driver.findElement(By.css(".d-flex:nth-child(3) .btn")).click()
    await driver.findElement(By.id("senha")).click()
    await driver.findElement(By.id("senha")).sendKeys("Joao54321")
    await driver.findElement(By.id("confirmar")).click()
    await driver.findElement(By.id("confirmar")).sendKeys("Joao54321")
    await driver.findElement(By.id("salvar")).click()
  })
})
