// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test_SocorroExpress_solicitacao', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test_SocorroExpress_solicitacao', async function() {
    await driver.get("http://127.0.0.1:5500/Front-end/html/solicitacao.html")
    await driver.manage().window().setRect({ width: 1084, height: 816 })
    await driver.findElement(By.id("localizacao-atual")).click()
    await driver.findElement(By.id("confirmar")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
  })
})
